# Generated by Django 4.1 on 2022-09-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_logauditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
