# Generated by Django 4.1 on 2022-09-20 01:06

from django.db import migrations

def initial_roles(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    group.objects.bulk_create(
        [
            group(name='Administrativo'),
            group(name='Profesor'),
            group(name='Estudiante')
        ]
    )
    
def revert_roles(apps, schema_editor):
    group = apps.get_model('auth', 'Group')
    group.objects.filter(
        name__in = [
            'Administrativo',
            'Profesor',
            'Estudiante'
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_seguimiento_observaciones'),
    ]

    operations = [
        migrations.RunPython(initial_roles, revert_roles)
    ]
