# Generated by Django 4.0.4 on 2022-09-21 01:08

from django.db import migrations
from django.db.models import Q

def permisos_iniciales(apps, schema_editor):
    groups = apps.get_model('auth', 'Group')
    permisos = apps.get_model('auth', 'permission')
    for group in groups.objects.all():
        if group.name == 'Administrativo':
            p = permisos.objects.filter(
                Q(content_type__model='estudiante') |
                Q(content_type__model='profesor') |
                Q(content_type__model='programa') |
                Q(content_type__model='materia') |
                Q(codename='view_seguimiento')
                )
        elif group.name == 'Profesor':
            p = permisos.objects.filter(
                Q(codename='view_estudiante') |
                Q(codename='view_programa') |
                Q(codename='change_programa') |
                Q(codename='view_profesor') |
                Q(codename='change_profesor') |
                Q(codename='view_materia') |
                Q(codename='change_materia') |
                Q(codename='view_seguimiento') |
                Q(codename='change_seguimiento') |
                Q(codename='add_seguimiento')
            )
        else:
            p = permisos.objects.filter(
                Q(codename='view_estudiante') |
                Q(codename='view_programa') |
                Q(codename='view_profesor') |
                Q(codename='view_materia') |
                Q(codename='view_seguimiento')
            )
        group.permissions.set(p)
        
def revert_permisos_iniciales(apps, schema_editor):
    groups = apps.get_model('auth', 'Group')
    for group in groups.objects.all():
        group.permissions.clear()

class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_auto_20220919_2006'),
    ]

    operations = [
        migrations.RunPython(permisos_iniciales, revert_permisos_iniciales)
    ]
